#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Runtime directory for AgentStudio configs / data / workspace.
# Defaults to ~/.agent-studio; override with `AGENT_STUDIO_HOME=/path ./deploy.sh ...`.
AGENT_STUDIO_HOME="${AGENT_STUDIO_HOME:-$HOME/.agent-studio}"

usage() {
  echo "Usage: $0 {build|up|down|restart|logs|init}"
  echo ""
  echo "  build    - Build the Docker image"
  echo "  up       - Initialize dirs/configs and start the service (detached)"
  echo "  down     - Stop and remove containers"
  echo "  restart  - Restart the service"
  echo "  logs     - Follow service logs"
  echo "  init     - Only initialize runtime directories and example configs"
  echo ""
  echo "AGENT_STUDIO_HOME: $AGENT_STUDIO_HOME"
  exit 1
}

write_env_file() {
  cat > "$SCRIPT_DIR/.env" << ENV
# Auto-generated by deploy.sh; do not commit.
# Override by exporting AGENT_STUDIO_HOME before running deploy.sh.
AGENT_STUDIO_HOME=$AGENT_STUDIO_HOME
ENV
}

init_dirs() {
  mkdir -p "$AGENT_STUDIO_HOME/config" \
           "$AGENT_STUDIO_HOME/claude/skills" \
           "$AGENT_STUDIO_HOME/claude/agents" \
           "$AGENT_STUDIO_HOME/data" \
           "$AGENT_STUDIO_HOME/logs" \
           "$AGENT_STUDIO_HOME/agent-workspace"
}

init_example_configs() {
  if [ ! -f "$AGENT_STUDIO_HOME/config/application-prod.yml" ]; then
    cat > "$AGENT_STUDIO_HOME/config/application-prod.yml" << 'YAML'
# AgentStudio 生产环境外置配置（profile: prod）
# 此文件会被 Spring Boot 自动加载，可覆盖镜像内的默认配置。
# 仅写入需要覆盖的字段；未覆盖的字段沿用镜像内 application.yml 的默认值。

agents:
  auth:
    # 必填：首次创建管理员账号的初始化令牌，请使用足够强的随机值。
    # 生成示例：openssl rand -hex 32
    initial-token: "REPLACE_WITH_STRONG_RANDOM_TOKEN"
    # 生产建议关闭通过 HTTP 调用初始化接口；如需保留，请确保前置反向代理已强制 HTTPS。
    allow-http-init: false

# 切换到 MySQL 时取消注释并修改：
# spring:
#   datasource:
#     url: jdbc:mysql://your-host:3306/agents?serverTimezone=UTC
#     username: agents
#     password: your-password

# 邮件 / Bark / OSS 等通知配置示例参见 DEPLOY.md
YAML
    echo "  Created $AGENT_STUDIO_HOME/config/application-prod.yml (example)"
    echo "  IMPORTANT: edit this file and set agents.auth.initial-token before exposing the service."
  fi

  if [ ! -f "$AGENT_STUDIO_HOME/claude/settings.json" ]; then
    cat > "$AGENT_STUDIO_HOME/claude/settings.json" << 'JSON'
{
  "permissions": {
    "allow": [],
    "deny": []
  }
}
JSON
    echo "  Created $AGENT_STUDIO_HOME/claude/settings.json (empty)"
  fi
}

if [ $# -eq 0 ]; then
  usage
fi

# Compose needs AGENT_STUDIO_HOME to interpolate volume paths; write it to deploy/.env
# so subsequent `docker compose ...` invocations (including manual ones) all work.
write_env_file

case "$1" in
  build)
    echo "Building base image..."
    docker build -f "$PROJECT_ROOT/docker/Dockerfile.base" \
      -t agents-base:latest \
      "$PROJECT_ROOT/docker"
    echo "Building application image..."
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" build --no-cache
    echo "Build complete."
    ;;
  up)
    echo "Using AGENT_STUDIO_HOME=$AGENT_STUDIO_HOME"
    echo "Initializing runtime directories..."
    init_dirs
    echo "Initializing example configs..."
    init_example_configs
    echo "Starting service..."
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" up -d
    echo ""
    echo "Service started. Access at http://localhost:8685"
    echo ""
    echo "Editable config: $AGENT_STUDIO_HOME/config/application-prod.yml"
    echo "Claude settings: $AGENT_STUDIO_HOME/claude/"
    echo "Workspace:       $AGENT_STUDIO_HOME/agent-workspace/"
    echo "Data (SQLite):   $AGENT_STUDIO_HOME/data/"
    echo "Logs:            $AGENT_STUDIO_HOME/logs/"
    ;;
  down)
    echo "Stopping service..."
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" down
    echo "Service stopped."
    ;;
  restart)
    echo "Restarting service..."
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" restart
    echo "Service restarted."
    ;;
  logs)
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" logs -f
    ;;
  init)
    echo "Using AGENT_STUDIO_HOME=$AGENT_STUDIO_HOME"
    echo "Initializing runtime directories..."
    init_dirs
    echo "Initializing example configs..."
    init_example_configs
    echo "Done."
    ;;
  *)
    usage
    ;;
esac
